services:
  nginx:
    image: nginx
    ports:
    - "80:80"
    - "443:443"
    restart: always
    volumes:
    - "./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
    - "./etc/nginx/proxy.conf:/etc/nginx/proxy.conf:ro"
